# tasks file for KongGateway
- name: Download deb
  get_url:
    url: "{{ kong_source_deb }}"
    dest: "{{ kong_working_dir }}"
    mode: 0600

- name: Install dependencies
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
  - "{{ kong_dependencies }}"

- name: Install deb
  apt:
    deb: https://packages.konghq.com/public/gateway-28/deb/ubuntu/pool/jammy/main/k/ko/kong_2.8.4/kong_2.8.4_amd64.deb

- name: Ensure kong group is present
  user:
    name: "{{ kong_group }}"
    state: present

- name: Ensure kong user is present
  user:
    name: "{{ kong_user }}"
    group: "{{ kong_group }}"

- name: Setup configuration
  template:
    src: kong.yml.j2
    dest: "{{ kong_conf_dest }}"
  notify:
  - reload kong

- name: Ensure log service directory exists
  file:
    path: "{{ kong_service_log_dir }}"
    state: directory
    owner: "{{ kong_user }}"
    group: "{{ kong_group }}"
    mode: 0755

- name: Setup init.d script
  template:
    src: kong.init.d.j2
    dest: "/etc/init.d/kong"
    mode: "u=rwx,g=rx,o=rx"
  notify:
  - restart kong

- name: Setup service
  service:
    name: kong
    state: "{{ kong_service_state }}"
    enabled: "{{ kong_service_enabled }}"

- name: "Install packages"
  apt: "name={{ item }} state=present"
  with_items:
  - postgresql
- name: "Installaing pip package"
  apt:
    name: pip
    state: present

- name: "Install Python packages"
  pip: "name={{ item }}  state=present"
  with_items:
  - psycopg2-binary

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
  - postgresql
